theme: jekyll-theme-minimal
title: IEC-CIM-Language-Localization
description: The CIM community's localisation repo for ontology files that only contain rdfs:Labels in languages other than English.
logo: /assets/img/logo.png
# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
iec-cim-lang-l10n_windows_zip_url: https://github.com/CIMug-org/IEC-CIM-Language-Localization/releases/download/1.0.0/IEC-CIM-Language-Localization-1.0.0.zip
iec-cim-lang-l10n_releases_url: https://github.com/CIMug-org/IEC-CIM-Language-Localization/releases
